### ISSUE TITLE
Discord.py support

### ISSUE THREAD

**Issue by Wamy-Dev** [jareer12/DiscordBotPanel#1]
I was messing around with this panel, and I was wanting to try to host my own bot, but it seems like this only supports js bots. 

You can "Install" the discord.py npm package, but it doesn't really recognize it. 

I think that this would be a very good way to load balance my discord bot, and I would like a way to use python on it.

**Comment by jareer12** [comment]
I'll more into it.

**Comment by jareer12** [comment]
Hey there @Wamy-Dev, Thank's for your suggestion on a new feature, but I think we'll only keep this panel for Discord.js bots and small node.js scripts, for now atleast.
