### ISSUE TITLE
[ERR_INVALID_ARG_VALUE] error 

### ISSUE THREAD

**Issue by TIMMLOPK** [jareer12/DiscordBotPanel#2]
I am interested this panel but I got  `[ERR_INVALID_ARG_VALUE]: The argument 'flags' is invalid. Received 'wr'` when I try to run.
This error is related to modules/collector.js.

**Comment by jareer12** [comment]
Hey there yeah, so turns out the source code is missing the `/database` folder. I'm working on improving the source code. For now you can manually create a `/database` folder in the directory and create files in the database folder called `/ram_usage.json` and `/cpu_usage.json`.

**Comment by jareer12** [comment]
Issue has been fixed.
